// Curated beginner curriculum for the Foundations module.
//
// This is the "hybrid" content model in practice: the lesson skeleton (order,
// teaching cards, intro) is authored and stable here, while the backend may
// later swap in AI-generated `exercises` per lesson. Until the Spring Boot
// `/foundations` endpoints are live, `useFoundations` serves this seed directly
// so the UI is fully clickable (see README "Integration Status").
import type { LearnTrack, LessonDetail } from "@/lib/types"

// Progress/completion here are defaults for the offline seed; once the backend
// is wired these come from the user's real attempt history.
export const FOUNDATIONS_SEED: LessonDetail[] = [
  // ── Survival track (Level 0 — "start here" phrases) ───────────────────────-
  // Sourced from the Korean Grammar Master Reference → "🆘 Level 0 — Survival
  // Korean": the phrases that get you through your first day in Korea.
  {
    id: "survival-1",
    track: "survival",
    order: 1,
    title: "Greetings & Goodbyes",
    subtitle: "Say hello — and the right kind of goodbye",
    level: "Intro",
    estimatedMinutes: 5,
    completed: false,
    progress: 0,
    intro:
      "안녕하세요 works with anyone, any time. The tricky part is goodbye: Korean has two, depending on who is leaving. If you walk away, tell the person staying 안녕히 계세요; if they leave and you stay, say 안녕히 가세요.",
    cards: [
      {
        hangul: "안녕하세요",
        romanization: "annyeong-haseyo",
        meaning: "Hello / Hi (polite). Safe with anyone, any time of day.",
        example: "안녕하세요, 저는 헨리예요.",
        exampleTranslation: "Hello, I'm Henry.",
        note: "Drop to 안녕 only with close friends — it means both 'hi' and 'bye'.",
      },
      {
        hangul: "안녕히 계세요",
        romanization: "annyeonghi gyeseyo",
        meaning: "Goodbye — said to the person staying (you are the one leaving).",
        example: "먼저 갈게요. 안녕히 계세요.",
        exampleTranslation: "I'll head off first. Goodbye.",
      },
      {
        hangul: "안녕히 가세요",
        romanization: "annyeonghi gaseyo",
        meaning: "Goodbye — said to the person leaving (you are staying).",
      },
      {
        hangul: "또 만나요",
        romanization: "tto mannayo",
        meaning: "See you again. A warm, friendly farewell.",
      },
      {
        hangul: "좋은 하루 보내세요",
        romanization: "joeun haru bonaeseyo",
        meaning: "Have a good day. Polite and very common.",
      },
    ],
    exercises: [
      {
        id: "survival-1-e1",
        type: "multiple-choice",
        prompt: "You're leaving the office; your coworkers are staying. What do you say?",
        options: ["안녕히 가세요", "안녕히 계세요", "또 만나요", "안녕"],
        answerIndex: 1,
        explanation: "You leave, they stay → 안녕히 계세요 (literally 'stay well').",
      },
      {
        id: "survival-1-e2",
        type: "multiple-choice",
        prompt: "Which greeting is safe with anyone, at any time?",
        options: ["안녕", "안녕히 가세요", "안녕하세요", "또 만나요"],
        answerIndex: 2,
        explanation: "안녕하세요 is the all-purpose polite greeting.",
      },
      {
        id: "survival-1-e3",
        type: "type-answer",
        prompt: "Type the casual word used for both 'hi' and 'bye' with close friends.",
        answer: "안녕",
        explanation: "안녕 is the casual form — only for close friends.",
      },
    ],
  },
  {
    id: "survival-2",
    track: "survival",
    order: 2,
    title: "Politeness & Self-Introduction",
    subtitle: "Thank you, sorry, and introducing yourself",
    level: "Intro",
    estimatedMinutes: 6,
    completed: false,
    progress: 0,
    intro:
      "A few set phrases carry most everyday politeness. Pair the formal 감사합니다 / 죄송합니다 with the lighter 고마워요 / 미안해요, and learn the fixed phrases Koreans expect when you introduce yourself.",
    cards: [
      {
        hangul: "감사합니다",
        romanization: "gamsahamnida",
        meaning: "Thank you (formal).",
        note: "고마워요 is the lighter, still-polite version for friends and coworkers.",
      },
      {
        hangul: "죄송합니다",
        romanization: "joesonghamnida",
        meaning: "I'm sorry (formal, sincere apology).",
        note: "미안해요 is lighter — for small, everyday slips.",
      },
      {
        hangul: "괜찮아요",
        romanization: "gwaenchanayo",
        meaning: "It's okay / no worries / I'm fine. Works as both reassurance and 'no thanks'.",
      },
      {
        hangul: "처음 뵙겠습니다",
        romanization: "cheoeum boepgesseumnida",
        meaning: "Nice to meet you (first meeting, formal).",
      },
      {
        hangul: "잘 부탁드립니다",
        romanization: "jal butakdeurimnida",
        meaning: "Please take care of me / I look forward to working with you. Said right after introducing yourself.",
        example: "저는 헨리예요. 잘 부탁드립니다.",
        exampleTranslation: "I'm Henry. I look forward to working with you.",
      },
      {
        hangul: "저는 ___에서 왔어요",
        romanization: "jeoneun ___ eseo wasseoyo",
        meaning: "I came from ___. Use 에서 (from) after the place name.",
        example: "저는 캄보디아에서 왔어요.",
        exampleTranslation: "I came from Cambodia.",
      },
    ],
    exercises: [
      {
        id: "survival-2-e1",
        type: "multiple-choice",
        prompt: "Your manager helped you a lot. What's the best formal 'thank you'?",
        options: ["고마워요", "감사합니다", "괜찮아요", "미안해요"],
        answerIndex: 1,
        explanation: "감사합니다 is the formal thank-you; 고마워요 is lighter/polite.",
      },
      {
        id: "survival-2-e2",
        type: "multiple-choice",
        prompt: "Meeting someone for the first time, formally. What do you say?",
        options: ["또 만나요", "처음 뵙겠습니다", "잘 가요", "괜찮아요"],
        answerIndex: 1,
        explanation: "처음 뵙겠습니다 is the formal first-meeting greeting.",
      },
      {
        id: "survival-2-e3",
        type: "type-answer",
        prompt: "Complete: 저는 캄보디아___ 왔어요 (I came from Cambodia). Type the particle.",
        answer: "에서",
        explanation: "에서 marks the place you came from → 캄보디아에서 왔어요.",
      },
    ],
  },
  {
    id: "survival-3",
    track: "survival",
    order: 3,
    title: "Ordering, Shopping & Emergencies",
    subtitle: "Cafés, prices, and asking for help",
    level: "Intro",
    estimatedMinutes: 7,
    completed: false,
    progress: 0,
    intro:
      "주세요 ('please give me') is your most useful word — point at anything and add it. Round it out with asking the price, paying, and the few phrases you need when you're stuck or lost.",
    cards: [
      {
        hangul: "이거 주세요",
        romanization: "igeo juseyo",
        meaning: "This one, please. Point and say it — works everywhere.",
        example: "이거 주세요. 그리고 물 주세요.",
        exampleTranslation: "This one, please. And water, please.",
      },
      {
        hangul: "계산해 주세요",
        romanization: "gyesanhae juseyo",
        meaning: "The check, please.",
      },
      {
        hangul: "이거 얼마예요?",
        romanization: "igeo eolmayeyo?",
        meaning: "How much is this?",
      },
      {
        hangul: "카드 돼요?",
        romanization: "kadeu dwaeyo?",
        meaning: "Can I pay by card?",
      },
      {
        hangul: "화장실 어디예요?",
        romanization: "hwajangsil eodiyeyo?",
        meaning: "Where is the bathroom?",
        note: "Swap 화장실 for 병원 (hospital) or 지하철역 (subway station).",
      },
      {
        hangul: "천천히 말해 주세요",
        romanization: "cheoncheonhi malhae juseyo",
        meaning: "Please speak slowly. Lifesaver when someone replies too fast.",
      },
    ],
    exercises: [
      {
        id: "survival-3-e1",
        type: "multiple-choice",
        prompt: "How do you ask the price of something?",
        options: ["이거 주세요", "이거 얼마예요?", "카드 돼요?", "계산해 주세요"],
        answerIndex: 1,
        explanation: "얼마예요? = 'how much is it?'.",
      },
      {
        id: "survival-3-e2",
        type: "multiple-choice",
        prompt: "You want to pay by card. What do you ask?",
        options: ["카드 돼요?", "계산해 주세요", "이거 주세요", "괜찮아요"],
        answerIndex: 0,
        explanation: "카드 돼요? literally asks 'does card work?'.",
      },
      {
        id: "survival-3-e3",
        type: "type-answer",
        prompt: "Complete the polite request 'please speak slowly': 천천히 말해 ___",
        answer: "주세요",
        explanation: "-아/어 주세요 makes a polite request → 말해 주세요.",
      },
    ],
  },

  // ── Alphabet track ────────────────────────────────────────────────────────
  {
    id: "alpha-1",
    track: "alphabet",
    order: 1,
    title: "Basic Vowels",
    subtitle: "The six core vowels of Hangul",
    level: "Intro",
    estimatedMinutes: 6,
    completed: false,
    progress: 0,
    intro:
      "Korean vowels are built from simple strokes. Learn these six first — every syllable you read will contain one. A vowel is written next to or below a consonant, never alone (the silent ㅇ holds its place).",
    cards: [
      { hangul: "ㅏ", romanization: "a", meaning: "like 'a' in father", example: "아", exampleTranslation: "ah" },
      { hangul: "ㅓ", romanization: "eo", meaning: "like 'u' in but", example: "어", exampleTranslation: "uh" },
      { hangul: "ㅗ", romanization: "o", meaning: "like 'o' in go", example: "오", exampleTranslation: "oh" },
      { hangul: "ㅜ", romanization: "u", meaning: "like 'oo' in food", example: "우", exampleTranslation: "oo" },
      { hangul: "ㅡ", romanization: "eu", meaning: "like 'oo' in good (lips flat)", example: "으", exampleTranslation: "eu" },
      { hangul: "ㅣ", romanization: "i", meaning: "like 'ee' in see", example: "이", exampleTranslation: "ee" },
    ],
    exercises: [
      {
        id: "alpha-1-e1",
        type: "multiple-choice",
        prompt: "Which vowel makes the 'a' (father) sound?",
        options: ["ㅓ", "ㅏ", "ㅜ", "ㅡ"],
        answerIndex: 1,
        explanation: "ㅏ is the open 'a' sound, as in father.",
      },
      {
        id: "alpha-1-e2",
        type: "multiple-choice",
        prompt: "What sound does ㅗ make?",
        options: ["eu", "u", "o", "eo"],
        answerIndex: 2,
        explanation: "ㅗ is 'o' as in go. The short line points up.",
      },
      {
        id: "alpha-1-e3",
        type: "type-answer",
        prompt: "Type the romanization of ㅣ",
        answer: "i",
        explanation: "ㅣ is 'i', a long 'ee' sound.",
      },
    ],
  },
  {
    id: "alpha-2",
    track: "alphabet",
    order: 2,
    title: "Basic Consonants",
    subtitle: "Nine everyday consonants",
    level: "Intro",
    estimatedMinutes: 8,
    completed: false,
    progress: 0,
    intro:
      "Consonants start most syllables. Their shapes hint at how your mouth makes the sound. Here are the nine most common ones — note that ㅇ is silent at the start of a syllable.",
    cards: [
      { hangul: "ㄱ", romanization: "g / k", meaning: "soft g, like 'g' in go", example: "가", exampleTranslation: "ga" },
      { hangul: "ㄴ", romanization: "n", meaning: "like 'n' in no", example: "나", exampleTranslation: "na" },
      { hangul: "ㄷ", romanization: "d / t", meaning: "like 'd' in do", example: "다", exampleTranslation: "da" },
      { hangul: "ㄹ", romanization: "r / l", meaning: "between 'r' and 'l'", example: "라", exampleTranslation: "ra" },
      { hangul: "ㅁ", romanization: "m", meaning: "like 'm' in mom", example: "마", exampleTranslation: "ma" },
      { hangul: "ㅂ", romanization: "b / p", meaning: "like 'b' in boy", example: "바", exampleTranslation: "ba" },
      { hangul: "ㅅ", romanization: "s", meaning: "like 's' in see", example: "사", exampleTranslation: "sa" },
      { hangul: "ㅇ", romanization: "(silent) / ng", meaning: "silent at the start; 'ng' at the end", example: "아", exampleTranslation: "a" },
      { hangul: "ㅈ", romanization: "j", meaning: "like 'j' in jump", example: "자", exampleTranslation: "ja" },
    ],
    exercises: [
      {
        id: "alpha-2-e1",
        type: "multiple-choice",
        prompt: "Which consonant is silent at the start of a syllable?",
        options: ["ㄴ", "ㅇ", "ㅁ", "ㅅ"],
        answerIndex: 1,
        explanation: "ㅇ is a placeholder at the start (아 = 'a'), and sounds 'ng' at the end of a syllable.",
      },
      {
        id: "alpha-2-e2",
        type: "multiple-choice",
        prompt: "What sound does ㅂ make?",
        options: ["m", "n", "b / p", "j"],
        answerIndex: 2,
        explanation: "ㅂ is 'b' (or a light 'p').",
      },
      {
        id: "alpha-2-e3",
        type: "type-answer",
        prompt: "Type the romanization of the syllable 마",
        answer: "ma",
        explanation: "ㅁ (m) + ㅏ (a) = 'ma'.",
      },
    ],
  },
  {
    id: "alpha-3",
    track: "alphabet",
    order: 3,
    title: "Building Syllables",
    subtitle: "Stacking consonants and vowels into blocks",
    level: "Beginner",
    estimatedMinutes: 7,
    completed: false,
    progress: 0,
    intro:
      "Hangul groups letters into square syllable blocks. A vertical vowel (ㅏㅓㅣ) goes to the right of the consonant; a horizontal vowel (ㅗㅜㅡ) goes below it. A third letter at the bottom is the 받침 (final consonant).",
    cards: [
      { hangul: "안", romanization: "an", meaning: "ㅇ + ㅏ + ㄴ — consonant, vowel, final", example: "안녕", exampleTranslation: "hi (annyeong)" },
      { hangul: "녕", romanization: "nyeong", meaning: "ㄴ + ㅕ + ㅇ — final ㅇ sounds 'ng'", example: "안녕", exampleTranslation: "hi" },
      { hangul: "고", romanization: "go", meaning: "ㄱ + ㅗ — horizontal vowel sits below", example: "고기", exampleTranslation: "meat" },
      { hangul: "기", romanization: "gi", meaning: "ㄱ + ㅣ — vertical vowel sits to the right", example: "고기", exampleTranslation: "meat" },
    ],
    exercises: [
      {
        id: "alpha-3-e1",
        type: "multiple-choice",
        prompt: "Where does a horizontal vowel like ㅗ go relative to its consonant?",
        options: ["To the right", "Below it", "Above it", "It stands alone"],
        answerIndex: 1,
        explanation: "Horizontal vowels (ㅗㅜㅡ) are written below the consonant; vertical ones (ㅏㅓㅣ) go to the right.",
      },
      {
        id: "alpha-3-e2",
        type: "type-answer",
        prompt: "Type the romanization of 고",
        answer: "go",
        explanation: "ㄱ (g) + ㅗ (o) = 'go'.",
      },
      {
        id: "alpha-3-e3",
        type: "multiple-choice",
        prompt: "In 안, what role does ㄴ play?",
        options: ["Starting consonant", "Vowel", "받침 (final consonant)", "It's silent"],
        answerIndex: 2,
        explanation: "ㄴ sits at the bottom as the 받침 (final consonant) of the block.",
      },
    ],
  },

  // ── Grammar track ───────────────────────────────────────────────────────--
  {
    id: "grammar-1",
    track: "grammar",
    order: 1,
    title: "Sentence Order & 이에요/예요",
    subtitle: "Korean is Subject–Object–Verb",
    level: "Beginner",
    estimatedMinutes: 8,
    completed: false,
    progress: 0,
    intro:
      "Korean puts the verb at the end: Subject–Object–Verb. The simplest sentence is 'A is B', formed with 이에요 (after a consonant) or 예요 (after a vowel) — the polite 'to be'.",
    cards: [
      {
        hangul: "이에요 / 예요",
        romanization: "ieyo / yeyo",
        meaning: "polite 'to be'. Use 이에요 after a consonant, 예요 after a vowel.",
        example: "저는 개발자예요.",
        exampleTranslation: "I am a developer.",
        note: "개발자 ends in a vowel → 예요. 학생 ends in a consonant → 학생이에요.",
      },
      {
        hangul: "S–O–V order",
        meaning: "The verb always comes last in a Korean sentence.",
        example: "저는 커피를 마셔요.",
        exampleTranslation: "I drink coffee. (lit. I coffee drink)",
      },
    ],
    exercises: [
      {
        id: "grammar-1-e1",
        type: "multiple-choice",
        prompt: "Where does the verb go in a Korean sentence?",
        options: ["First", "After the subject", "At the very end", "It's optional"],
        answerIndex: 2,
        explanation: "Korean is Subject–Object–Verb: the verb always comes last.",
      },
      {
        id: "grammar-1-e2",
        type: "multiple-choice",
        prompt: "학생 (student) ends in a consonant. Which 'to be' form is correct?",
        options: ["학생예요", "학생이에요", "학생요", "학생이에"],
        answerIndex: 1,
        explanation: "After a consonant, use 이에요 → 학생이에요 ('I am a student').",
      },
      {
        id: "grammar-1-e3",
        type: "type-answer",
        prompt: "Complete: 개발자___ (I am a developer). Type the ending.",
        answer: "예요",
        explanation: "개발자 ends in a vowel, so use 예요 → 개발자예요.",
      },
    ],
  },
  {
    id: "grammar-2",
    track: "grammar",
    order: 2,
    title: "Topic & Subject Particles",
    subtitle: "은/는 and 이/가",
    level: "Beginner",
    estimatedMinutes: 9,
    completed: false,
    progress: 0,
    intro:
      "Particles tag the role of a word. 은/는 marks the topic ('as for…'); 이/가 marks the subject (often new or emphasized info). Choose the form by whether the word ends in a consonant or a vowel.",
    cards: [
      {
        hangul: "은 / 는",
        romanization: "eun / neun",
        meaning: "topic marker. 은 after a consonant, 는 after a vowel.",
        example: "저는 한국에 살아요.",
        exampleTranslation: "As for me, I live in Korea.",
      },
      {
        hangul: "이 / 가",
        romanization: "i / ga",
        meaning: "subject marker. 이 after a consonant, 가 after a vowel.",
        example: "고양이가 있어요.",
        exampleTranslation: "There is a cat.",
      },
    ],
    exercises: [
      {
        id: "grammar-2-e1",
        type: "multiple-choice",
        prompt: "저 (I) ends in a vowel. Which topic particle attaches?",
        options: ["은", "는", "이", "가"],
        answerIndex: 1,
        explanation: "After a vowel the topic particle is 는 → 저는.",
      },
      {
        id: "grammar-2-e2",
        type: "multiple-choice",
        prompt: "책 (book) ends in a consonant. Which subject particle is correct?",
        options: ["가", "는", "이", "를"],
        answerIndex: 2,
        explanation: "After a consonant the subject particle is 이 → 책이.",
      },
      {
        id: "grammar-2-e3",
        type: "type-answer",
        prompt: "Add the topic particle to 개발자: 개발자___",
        answer: "는",
        explanation: "개발자 ends in a vowel → 는 (개발자는).",
      },
    ],
  },
  {
    id: "grammar-3",
    track: "grammar",
    order: 3,
    title: "The Object Particle 을/를",
    subtitle: "Marking what the verb acts on",
    level: "Beginner",
    estimatedMinutes: 6,
    completed: false,
    progress: 0,
    intro:
      "The object particle marks the thing receiving the action. Use 을 after a consonant and 를 after a vowel. It sits right before the verb, matching the S–O–V order.",
    cards: [
      {
        hangul: "을 / 를",
        romanization: "eul / reul",
        meaning: "object marker. 을 after a consonant, 를 after a vowel.",
        example: "코드를 작성해요.",
        exampleTranslation: "I write code.",
        note: "코드 ends in a vowel → 를. 책 ends in a consonant → 책을.",
      },
    ],
    exercises: [
      {
        id: "grammar-3-e1",
        type: "multiple-choice",
        prompt: "물 (water) ends in a consonant. Which object particle is correct?",
        options: ["를", "을", "가", "는"],
        answerIndex: 1,
        explanation: "After a consonant use 을 → 물을 마셔요 ('I drink water').",
      },
      {
        id: "grammar-3-e2",
        type: "type-answer",
        prompt: "Add the object particle to 커피 (coffee): 커피___",
        answer: "를",
        explanation: "커피 ends in a vowel → 를 (커피를).",
      },
      {
        id: "grammar-3-e3",
        type: "multiple-choice",
        prompt: "Where does the object (with 을/를) sit in the sentence?",
        options: ["At the start", "Right before the verb", "After the verb", "Anywhere"],
        answerIndex: 1,
        explanation: "Objects come right before the final verb in S–O–V order.",
      },
    ],
  },
  {
    id: "grammar-4",
    track: "grammar",
    order: 4,
    title: "Present Tense 요-form",
    subtitle: "Everyday polite verbs",
    level: "Elementary",
    estimatedMinutes: 10,
    completed: false,
    progress: 0,
    intro:
      "The 요 ending makes a verb polite and is the workhorse of daily speech. Drop 다 from the dictionary form, then add 아요 (if the last vowel is ㅏ/ㅗ) or 어요 (otherwise). 하다 verbs become 해요.",
    cards: [
      {
        hangul: "가다 → 가요",
        romanization: "gada → gayo",
        meaning: "stem vowel ㅏ → add 아요 (the ㅏ merges).",
        example: "회사에 가요.",
        exampleTranslation: "I go to the office.",
      },
      {
        hangul: "먹다 → 먹어요",
        romanization: "meokda → meogeoyo",
        meaning: "stem vowel ㅓ → add 어요.",
        example: "점심을 먹어요.",
        exampleTranslation: "I eat lunch.",
      },
      {
        hangul: "하다 → 해요",
        romanization: "hada → haeyo",
        meaning: "하다 verbs are irregular → 해요.",
        example: "배포를 해요.",
        exampleTranslation: "I do the deployment.",
      },
    ],
    exercises: [
      {
        id: "grammar-4-e1",
        type: "multiple-choice",
        prompt: "What is the polite present form of 하다 (to do)?",
        options: ["하아요", "하어요", "해요", "하요"],
        answerIndex: 2,
        explanation: "하다 is irregular: it becomes 해요.",
      },
      {
        id: "grammar-4-e2",
        type: "multiple-choice",
        prompt: "먹다's last stem vowel is ㅓ. Which ending attaches?",
        options: ["아요", "어요", "해요", "이에요"],
        answerIndex: 1,
        explanation: "When the stem vowel is not ㅏ/ㅗ, add 어요 → 먹어요.",
      },
      {
        id: "grammar-4-e3",
        type: "type-answer",
        prompt: "Conjugate 가다 (to go) into the polite present form.",
        answer: "가요",
        explanation: "Stem vowel ㅏ + 아요, which merges to 가요.",
      },
    ],
  },
  // ── Daily Power Grammar (Heang's interview pack) ──
  // The ⭐ priority patterns from the Korean Grammar Master Reference: the
  // 10 endings that cover ~80% of daily/workplace Korean, split across two
  // lessons. Examples stay dev/workplace-themed to match the rest of the track.
  {
    id: "grammar-5",
    track: "grammar",
    order: 5,
    title: "Daily Power Grammar I",
    subtitle: "Opinion, result, experience & intention",
    level: "Elementary",
    estimatedMinutes: 12,
    completed: false,
    progress: 0,
    intro:
      "These five endings carry a huge share of everyday and workplace Korean. Learn them as whole patterns: attach each to a verb to soften an opinion, describe how things turned out, talk about experience, state a plan, or say what you want.",
    cards: [
      {
        hangul: "-(으)ㄴ/는 것 같아요",
        romanization: "-(eu)n/neun geot gatayo",
        meaning: "I think… / it seems…. Softens an opinion. Verb + 는 것 같아요; descriptive or past + -(으)ㄴ 것 같아요.",
        example: "이 버그는 캐시 문제인 것 같아요.",
        exampleTranslation: "I think this bug is a cache issue.",
        note: "Great for meetings — sounds less blunt than stating it as fact.",
      },
      {
        hangul: "-게 됐어요",
        romanization: "-ge dwaesseoyo",
        meaning: "I ended up / came to (do). Marks a change of situation, often outside your control.",
        example: "이 팀에서 일하게 됐어요.",
        exampleTranslation: "I ended up working on this team.",
      },
      {
        hangul: "-아/어 본 적이 있어요",
        romanization: "-a/eo bon jeogi isseoyo",
        meaning: "I have (ever) done…, talking about experience. Attach 본 적이 있어요 to the -아/어 form.",
        example: "코드 리뷰를 해 본 적이 있어요.",
        exampleTranslation: "I've done code review before.",
        note: "Negative: -아/어 본 적이 없어요 = 'I've never…'.",
      },
      {
        hangul: "-(으)려고 해요",
        romanization: "-(eu)ryeogo haeyo",
        meaning: "I plan / intend to…. Stem + -(으)려고 해요.",
        example: "내일 새 기능을 배포하려고 해요.",
        exampleTranslation: "I'm planning to deploy the new feature tomorrow.",
      },
      {
        hangul: "-고 싶어요",
        romanization: "-go sipeoyo",
        meaning: "I want to (do). Attach 고 싶어요 to the verb stem.",
        example: "백엔드 개발자가 되고 싶어요.",
        exampleTranslation: "I want to become a backend developer.",
        note: "For someone else's wish use -고 싶어 해요.",
      },
    ],
    exercises: [
      {
        id: "grammar-5-e1",
        type: "multiple-choice",
        prompt: "Which pattern softens an opinion ('I think… / it seems…')?",
        options: ["-게 됐어요", "-(으)ㄴ/는 것 같아요", "-고 싶어요", "-(으)려고 해요"],
        answerIndex: 1,
        explanation: "-(으)ㄴ/는 것 같아요 frames a statement as your impression, not a hard fact.",
      },
      {
        id: "grammar-5-e2",
        type: "multiple-choice",
        prompt: "How do you say 'I'm planning to deploy'?",
        options: ["배포하고 싶어요", "배포하게 됐어요", "배포하려고 해요", "배포하는 것 같아요"],
        answerIndex: 2,
        explanation: "-(으)려고 해요 states an intention/plan → 배포하려고 해요.",
      },
      {
        id: "grammar-5-e3",
        type: "type-answer",
        prompt: "Complete: 백엔드 개발자가 되___ 싶어요 (I want to become a backend developer). Type the ending.",
        answer: "고",
        explanation: "Verb stem + 고 싶어요 expresses desire → 되고 싶어요.",
      },
    ],
  },
  {
    id: "grammar-6",
    track: "grammar",
    order: 6,
    title: "Daily Power Grammar II",
    subtitle: "Obligation, requests, permission & reasons",
    level: "Elementary",
    estimatedMinutes: 12,
    completed: false,
    progress: 0,
    intro:
      "The other five high-frequency endings handle obligation, polite requests, permission, prohibition, and giving a reason. Together with Lesson I they cover most of what you need in daily and workplace conversations.",
    cards: [
      {
        hangul: "-아/어야 돼요",
        romanization: "-a/eoya dwaeyo",
        meaning: "I have to / must (do). Use the -아/어 form + 야 돼요 (also 야 해요).",
        example: "버그를 먼저 고쳐야 돼요.",
        exampleTranslation: "I have to fix the bug first.",
      },
      {
        hangul: "-아/어 주세요",
        romanization: "-a/eo juseyo",
        meaning: "Please do… (for me). Polite request: -아/어 form + 주세요.",
        example: "이 코드를 확인해 주세요.",
        exampleTranslation: "Please check this code.",
      },
      {
        hangul: "-아/어도 돼요",
        romanization: "-a/eodo dwaeyo",
        meaning: "It's OK to / you may…. -아/어 form + 도 돼요. As a question, it asks permission.",
        example: "이거 지금 머지해도 돼요?",
        exampleTranslation: "Is it OK to merge this now?",
      },
      {
        hangul: "-(으)면 안 돼요",
        romanization: "-(eu)myeon an dwaeyo",
        meaning: "You must not / can't…. Condition -(으)면 + 안 돼요 = it's not allowed.",
        example: "main 브랜치에 직접 푸시하면 안 돼요.",
        exampleTranslation: "You can't push directly to the main branch.",
      },
      {
        hangul: "-거든요",
        romanization: "-geodeunyo",
        meaning: "…you see / it's because…. Gives a reason or background the listener didn't know yet.",
        example: "어제 늦게까지 일했거든요.",
        exampleTranslation: "(It's because) I worked late yesterday, you see.",
        note: "Conversational — explains the situation behind what you just said.",
      },
    ],
    exercises: [
      {
        id: "grammar-6-e1",
        type: "multiple-choice",
        prompt: "Which pattern asks permission ('May I… / Is it OK to…?')?",
        options: ["-아/어도 돼요", "-(으)면 안 돼요", "-아/어야 돼요", "-거든요"],
        answerIndex: 0,
        explanation: "-아/어도 돼요 as a question asks whether something is allowed.",
      },
      {
        id: "grammar-6-e2",
        type: "multiple-choice",
        prompt: "Complete the polite request: 이 코드를 확인해 ___.",
        options: ["주세요", "야 돼요", "도 돼요", "거든요"],
        answerIndex: 0,
        explanation: "-아/어 주세요 = 'please do for me' → 확인해 주세요.",
      },
      {
        id: "grammar-6-e3",
        type: "type-answer",
        prompt: "Complete: 버그를 먼저 고쳐___ 돼요 (I have to fix the bug first). Type the ending.",
        answer: "야",
        explanation: "-아/어야 돼요 expresses obligation → 고쳐야 돼요.",
      },
    ],
  },

  // ── Numbers, verbs & irregulars (from the Grammar Master Reference) ───────-
  // Levels 2–3 of the Korean Lessons curriculum: the two number systems and
  // counters, formal speech + tenses, negation, and irregular-verb groups.
  {
    id: "grammar-7",
    track: "grammar",
    order: 7,
    title: "Sino-Korean Numbers",
    subtitle: "Money, dates, and minutes",
    level: "Elementary",
    estimatedMinutes: 9,
    completed: false,
    progress: 0,
    intro:
      "Korean has two number systems. Sino-Korean (from Chinese) is used for money (원), dates (년/월/일), minutes (분), and phone numbers. Learn 1–10, then build everything else by stacking tens and ones.",
    cards: [
      {
        hangul: "일 이 삼 사 오",
        romanization: "il i sam sa o",
        meaning: "1, 2, 3, 4, 5 (Sino-Korean).",
      },
      {
        hangul: "육 칠 팔 구 십",
        romanization: "yuk chil pal gu sip",
        meaning: "6, 7, 8, 9, 10 (Sino-Korean).",
      },
      {
        hangul: "십일 · 이십오 · 사십칠",
        romanization: "sibil · isibo · sasipchil",
        meaning: "Build numbers as (tens)+(ones): 11, 25, 47.",
        note: "25 = 이십오 (2·10·5), 47 = 사십칠 (4·10·7).",
      },
      {
        hangul: "백 · 천 · 만",
        romanization: "baek · cheon · man",
        meaning: "100 · 1,000 · 10,000. Korean groups large numbers by 만 (ten-thousands).",
        example: "15,000 = 만오천",
        exampleTranslation: "(10,000 + 5,000)",
      },
      {
        hangul: "원 / 년 / 월 / 일 / 분",
        romanization: "won / nyeon / wol / il / bun",
        meaning: "Sino is used for money, year, month, day, and minutes.",
        example: "오후 세 시 삼십 분",
        exampleTranslation: "3:30 PM (hours native, minutes Sino)",
      },
    ],
    exercises: [
      {
        id: "grammar-7-e1",
        type: "multiple-choice",
        prompt: "Which number system do you use for money (원) and dates?",
        options: ["Native Korean", "Sino-Korean", "Either one", "Neither"],
        answerIndex: 1,
        explanation: "Money, dates, and minutes all use Sino-Korean numbers.",
      },
      {
        id: "grammar-7-e2",
        type: "multiple-choice",
        prompt: "What number is 이십오?",
        options: ["15", "25", "52", "205"],
        answerIndex: 1,
        explanation: "이(2)·십(10)·오(5) = 25.",
      },
      {
        id: "grammar-7-e3",
        type: "type-answer",
        prompt: "Type the romanization of 천 (1,000).",
        answer: "cheon",
        explanation: "천 = cheon = 1,000.",
      },
    ],
  },
  {
    id: "grammar-8",
    track: "grammar",
    order: 8,
    title: "Native Numbers & Counters",
    subtitle: "Counting people, things, age & hours",
    level: "Elementary",
    estimatedMinutes: 10,
    completed: false,
    progress: 0,
    intro:
      "Native Korean numbers count people, objects, age, and hours. Before a counter, the first few numbers shorten: 하나→한, 둘→두, 셋→세, 넷→네, 스물→스무. The number+counter sits right after the noun.",
    cards: [
      {
        hangul: "하나 둘 셋 넷 다섯",
        romanization: "hana dul set net daseot",
        meaning: "1–5 (native Korean).",
      },
      {
        hangul: "한 · 두 · 세 · 네 · 스무",
        romanization: "han · du · se · ne · seumu",
        meaning: "Shortened forms used directly before a counter.",
        example: "사과 두 개",
        exampleTranslation: "two apples (개 = general counter)",
      },
      {
        hangul: "개 · 명 · 잔 · 마리",
        romanization: "gae · myeong · jan · mari",
        meaning: "Counters: things · people · cups · animals.",
        example: "커피 한 잔, 고양이 두 마리",
        exampleTranslation: "one coffee, two cats",
      },
      {
        hangul: "살",
        romanization: "sal",
        meaning: "Counter for age (native numbers).",
        example: "저는 스물다섯 살이에요.",
        exampleTranslation: "I'm 25 years old.",
      },
      {
        hangul: "시 + 분",
        romanization: "si + bun",
        meaning: "Telling time mixes systems: hours are native (시), minutes are Sino (분).",
        example: "세 시 이십오 분",
        exampleTranslation: "3:25",
      },
    ],
    exercises: [
      {
        id: "grammar-8-e1",
        type: "multiple-choice",
        prompt: "How do you say 'two cups of coffee'?",
        options: ["커피 둘 잔", "커피 두 잔", "커피 이 잔", "커피 두 개"],
        answerIndex: 1,
        explanation: "둘 shortens to 두 before the counter 잔 → 커피 두 잔.",
      },
      {
        id: "grammar-8-e2",
        type: "multiple-choice",
        prompt: "Which uses NATIVE Korean numbers?",
        options: ["Minutes (분)", "Money (원)", "Age (살)", "Year (년)"],
        answerIndex: 2,
        explanation: "Age, people, things, and hours use native numbers; minutes/money/dates use Sino.",
      },
      {
        id: "grammar-8-e3",
        type: "type-answer",
        prompt: "Type the shortened form of 하나 used before a counter (e.g. 한 ___).",
        answer: "한",
        explanation: "하나 → 한 before a counter (한 개, 한 잔).",
      },
    ],
  },
  {
    id: "grammar-9",
    track: "grammar",
    order: 9,
    title: "Tenses & Formal Speech",
    subtitle: "Past, future, and the -ㅂ니다 register",
    level: "Elementary",
    estimatedMinutes: 11,
    completed: false,
    progress: 0,
    intro:
      "Beyond the casual-polite 요-form, you need the formal -(스)ㅂ니다 for work and presentations, the past tense -았/었어요, and the future -(으)ㄹ 거예요. The past and future follow the same vowel logic you already know.",
    cards: [
      {
        hangul: "-(스)ㅂ니다",
        romanization: "-(seu)mnida",
        meaning: "Formal-polite ending for the office, reports, and presentations. Vowel stem → -ㅂ니다; consonant stem → -습니다.",
        example: "가다 → 갑니다 · 먹다 → 먹습니다",
        exampleTranslation: "goes / eats (formal)",
        note: "Question form swaps 다 for 까? → 갑니까? 먹습니까?",
      },
      {
        hangul: "-았/었어요",
        romanization: "-at/eosseoyo",
        meaning: "Past tense. Same vowel rule as 요-form, with ㅆ added: ㅏ/ㅗ → 았어요, otherwise → 었어요; 하다 → 했어요.",
        example: "가다 → 갔어요 · 먹다 → 먹었어요",
        exampleTranslation: "went / ate",
      },
      {
        hangul: "-(으)ㄹ 거예요",
        romanization: "-(eu)l geoyeyo",
        meaning: "Future / probability. Vowel stem → -ㄹ 거예요; consonant stem → -을 거예요.",
        example: "내일 한국에 갈 거예요.",
        exampleTranslation: "I'll go to Korea tomorrow.",
      },
    ],
    exercises: [
      {
        id: "grammar-9-e1",
        type: "multiple-choice",
        prompt: "Giving a presentation to your team. Which ending fits best?",
        options: ["-아/어요", "-(스)ㅂ니다", "반말 (casual)", "-거든요"],
        answerIndex: 1,
        explanation: "-(스)ㅂ니다 is the formal register for presentations and reports.",
      },
      {
        id: "grammar-9-e2",
        type: "multiple-choice",
        prompt: "What is the past tense of 가다 (to go)?",
        options: ["가요", "갈 거예요", "갔어요", "갑니다"],
        answerIndex: 2,
        explanation: "Stem vowel ㅏ + 았어요, contracted → 갔어요.",
      },
      {
        id: "grammar-9-e3",
        type: "type-answer",
        prompt: "Conjugate 가다 into the future ('will go'): ___ 거예요. Type the first word.",
        answer: "갈",
        explanation: "Vowel stem + -ㄹ 거예요 → 갈 거예요.",
      },
    ],
  },
  {
    id: "grammar-10",
    track: "grammar",
    order: 10,
    title: "Negation — 안 & 못",
    subtitle: "Saying don't, can't, and not",
    level: "Elementary",
    estimatedMinutes: 7,
    completed: false,
    progress: 0,
    intro:
      "Two short words handle most negation. 안 means 'don't' (a choice); 못 means 'can't' (ability — even if you want to). Both go right before the verb. There's also a longer, more formal -지 않다.",
    cards: [
      {
        hangul: "안 + verb",
        romanization: "an",
        meaning: "Simple negation ('don't / not'), common in speech.",
        example: "안 가요.",
        exampleTranslation: "I don't go.",
        note: "With 하다 verbs, 안 goes before 하다: 공부 안 해요 (not 안 공부해요).",
      },
      {
        hangul: "못 + verb",
        romanization: "mot",
        meaning: "Cannot — lack of ability, even if you want to.",
        example: "오늘은 못 가요.",
        exampleTranslation: "I can't go today.",
      },
      {
        hangul: "-지 않다",
        romanization: "-ji anta",
        meaning: "Longer, more formal/written negation.",
        example: "가지 않아요.",
        exampleTranslation: "I do not go.",
      },
      {
        hangul: "안 vs 못",
        meaning: "안 = choice (won't/don't); 못 = inability (can't).",
        example: "안 먹어요 / 못 먹어요",
        exampleTranslation: "I don't eat (choice) / I can't eat (e.g. allergy)",
      },
    ],
    exercises: [
      {
        id: "grammar-10-e1",
        type: "multiple-choice",
        prompt: "You're sick and physically cannot come in. Which is correct?",
        options: ["안 가요", "못 가요", "가지 않아요", "안 갈 거예요"],
        answerIndex: 1,
        explanation: "못 expresses inability → 못 가요 ('I can't go').",
      },
      {
        id: "grammar-10-e2",
        type: "multiple-choice",
        prompt: "Where does 안 go with 공부하다 (to study)?",
        options: ["안 공부해요", "공부 안 해요", "공부해 안요", "공부하 안다"],
        answerIndex: 1,
        explanation: "With 하다 verbs, 안 splits the noun and 하다 → 공부 안 해요.",
      },
      {
        id: "grammar-10-e3",
        type: "type-answer",
        prompt: "Make 먹어요 negative using 안 (two words).",
        answer: "안 먹어요",
        explanation: "안 goes right before the verb → 안 먹어요.",
      },
    ],
  },
  {
    id: "grammar-11",
    track: "grammar",
    order: 11,
    title: "Irregular Verbs",
    subtitle: "Stems that change before a vowel",
    level: "Elementary",
    estimatedMinutes: 12,
    completed: false,
    progress: 0,
    intro:
      "Some verb stems change when an ending starts with a vowel. These four groups cover most of what you'll meet daily. Learn the pattern, then the common exceptions that stay regular.",
    cards: [
      {
        hangul: "ㅂ irregular (ㅂ → 우)",
        meaning: "돕다 → 도와요 (help), 춥다 → 추워요 (cold), 맵다 → 매워요 (spicy).",
        note: "Regular exceptions: 입다 (wear), 잡다 (catch) — no change.",
      },
      {
        hangul: "ㄷ irregular (ㄷ → ㄹ)",
        meaning: "듣다 → 들어요 (listen), 걷다 → 걸어요 (walk), 묻다 → 물어요 (ask).",
        note: "Regular exceptions: 받다 (receive), 닫다 (close), 믿다 (believe).",
      },
      {
        hangul: "르 irregular (most common)",
        meaning: "모르다 → 몰라요 (not know), 빠르다 → 빨라요 (fast), 부르다 → 불러요 (call/sing).",
      },
      {
        hangul: "ㅡ irregular (ㅡ drops)",
        meaning: "쓰다 → 써요 (write), 아프다 → 아파요 (sick), 바쁘다 → 바빠요 (busy).",
        note: "If the vowel before ㅡ is ㅏ/ㅗ use 아요, otherwise 어요.",
      },
    ],
    exercises: [
      {
        id: "grammar-11-e1",
        type: "multiple-choice",
        prompt: "What is 듣다 (to listen) in the -아/어요 form?",
        options: ["듣어요", "들어요", "듣아요", "들려요"],
        answerIndex: 1,
        explanation: "ㄷ → ㄹ before a vowel ending → 들어요.",
      },
      {
        id: "grammar-11-e2",
        type: "multiple-choice",
        prompt: "Conjugate 모르다 (to not know) into -아/어요.",
        options: ["모르요", "모러요", "몰라요", "모라요"],
        answerIndex: 2,
        explanation: "르 irregular → 몰라요.",
      },
      {
        id: "grammar-11-e3",
        type: "type-answer",
        prompt: "Conjugate 춥다 (to be cold) into the -아/어요 form.",
        answer: "추워요",
        explanation: "ㅂ → 우, then + 어요 → 추워요.",
      },
    ],
  },
]

export function seedLessonsByTrack(track: LearnTrack): LessonDetail[] {
  return FOUNDATIONS_SEED.filter((lesson) => lesson.track === track).sort((a, b) => a.order - b.order)
}

export function seedLessonById(id: string): LessonDetail | undefined {
  return FOUNDATIONS_SEED.find((lesson) => lesson.id === id)
}
